  global:
LW_ACCESS_TOKEN=LWINTROB_9750095FBB6D3CB5A051800B84560A87A4AF3AF9CCDBD81 See Integrate inline scanner to get your access token
LW_ACCOUNT_NAME=my_company
before_install:
docker pull mongo:latest 
script:
curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
chmod u+x lw-scanner
./lw-scanner image evaluate image_name tag --build-id $TRAVIS_BUILD_ID --build-plan $TRAVIS_JOB_NAME